<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busi.proto

namespace App\Grpc\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DtmRequest request sent to dtm server
 *
 * Generated from protobuf message <code>busi.BusiReq</code>
 */
class BusiReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Amount = 1;</code>
     */
    protected $Amount = 0;
    /**
     * Generated from protobuf field <code>string TransOutResult = 2;</code>
     */
    protected $TransOutResult = '';
    /**
     * Generated from protobuf field <code>string TransInResult = 3;</code>
     */
    protected $TransInResult = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Amount
     *     @type string $TransOutResult
     *     @type string $TransInResult
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Busi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Amount = 1;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->Amount;
    }

    /**
     * Generated from protobuf field <code>int64 Amount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TransOutResult = 2;</code>
     * @return string
     */
    public function getTransOutResult()
    {
        return $this->TransOutResult;
    }

    /**
     * Generated from protobuf field <code>string TransOutResult = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransOutResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransOutResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TransInResult = 3;</code>
     * @return string
     */
    public function getTransInResult()
    {
        return $this->TransInResult;
    }

    /**
     * Generated from protobuf field <code>string TransInResult = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransInResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransInResult = $var;

        return $this;
    }

}

