<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busi.proto

namespace App\Grpc\Message;

/**
 * The dtm service definition.
 *
 * Protobuf type <code>busi.Busi</code>
 */
interface BusiInterface
{
    /**
     * Method <code>transIn</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transIn(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOut</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOut(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInRevert</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInRevert(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutRevert</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutRevert(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInConfirm</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInConfirm(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutConfirm</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutConfirm(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>xaNotify</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function xaNotify(\Google\Protobuf\GPBEmpty $request);

    /**
     * Method <code>transInXa</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInXa(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutXa</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutXa(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInTcc</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInTcc(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutTcc</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutTcc(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInTccNested</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInTccNested(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInBSaga</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInBSaga(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutBSaga</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutBSaga(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInRevertBSaga</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInRevertBSaga(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutRevertBSaga</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutRevertBSaga(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutHeaderYes</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutHeaderYes(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutHeaderNo</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutHeaderNo(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInRedis</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInRedis(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutRedis</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutRedis(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transInRevertRedis</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transInRevertRedis(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>transOutRevertRedis</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function transOutRevertRedis(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>queryPrepared</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \App\Grpc\Message\BusiReply
     */
    public function queryPrepared(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>queryPreparedB</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function queryPreparedB(\App\Grpc\Message\BusiReq $request);

    /**
     * Method <code>queryPreparedRedis</code>
     *
     * @param \App\Grpc\Message\BusiReq $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function queryPreparedRedis(\App\Grpc\Message\BusiReq $request);

}

